[package]
name = "shrimp_lang"
version = "0.1.0"
edition = "2018"
license_file = "./LICENSE.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "*"
anyhow = "*"